### ISSUE TITLE
Publish schedule

### ISSUE THREAD

**Issue by meis** [barcelonapm/perl-and-friends-2017#22]
- Make schedule
- Announce it

**Comment by ureesoriano** [comment]
Just added a branch 'schedule':  https://github.com/barcelonapm/perl-and-friends-2017/tree/schedule
It adds a 'schedule' section to the page with content, as of now, blatantly stolen from last year's site.

TODO:
* Fill in the gaps

Could I get access to the schedule spreadsheet, please?
