### ISSUE TITLE
preconf

### ISSUE THREAD

**Issue by jluis** [barcelonapm/perl-and-friends-2017#30]

**Comment by jluis** [comment]
Ayer fui a comer al maestro ( la cerveceria de rambla de cataluña valencia) http://maestrobcn.com/ 
Y me dijereso que para ungrupo 10 a 20 no habri problema de reserva y que esta bastante tranquilo un viernes hasta las 20h  21h

**Comment by ureesoriano** [comment]
Thanks por la sugerencia, @jluis !

Pica un poco más de lo que esperaría (nos iremos a 20€/pers); pero más allá de esto tiene buena pinta. Works for me :+1: 
Link a la carta: http://maestrobcn.com/files/2017/06/carta_maestro_es.pdf

**Comment by ureesoriano** [comment]
En el anterior meeting, comentamos con @diegok :
* Preparar un doodle para registrar asistentes
* Preparar un mail en el que se informa a los asistentes del preconf event (con link al doodle)

He preparado un doodle: https://doodle.com/poll/32pzsy8znufxyggn
Un par de notas:
* Cada asistente solo puede ver su voto
* Una única fecha disponible (viernes 3) y respuesta de si/no
* Está configurada con mi email personal; se puede editar, pero


Por último, paso una propuesta de email para los atendees. Cualquier opinión - por quisquillosa que sea - es más que bienvenida:
```
Hi o/

Yep, 'Perl & Friends 2017' is just around the corner. 
We ourselves can't wait to get started, so we thought about organising a proper warm-up.

"Preconference event" is the name of the game and, for convenience, it's going to take place at a bar close to the conference venue.
Good beer, soda or food if you are hungry: pick your own weapon.
Come join us at 19h.

Please, do let us know if you will be atending the Preconf event:
https://doodle.com/poll/32pzsy8znufxyggn

Cheers,
Barcelona Perl Monguers.


PS: The exact location of the event will be published during this week.
```

**Comment by diegok** [comment]
Yo el doodle haria que todos vean quienes/cuantos van. El mail esta genial! :+1:

**Comment by ureesoriano** [comment]
He hecho el doodle público 👌
Creo que no demoraría más el enviar el mail. Podríamos hacerlo hoy mismo?

**Comment by ureesoriano** [comment]
He llamado para reservar en el Maestró para el viernes a las 19h.
Por ahora he reservado para 20. Me han dicho que si durante la semana llamamos para ajustar el número de gente no hay problema.

**Comment by diegok** [comment]
Enviado!
