### ISSUE TITLE
Breakfast

### ISSUE THREAD

**Issue by frankiejol** [barcelonapm/perl-and-friends-2017#31]
- [ ] Pastas
- [ ] Cafetera Dolce Gusto
- [ ] Cápsulas Dolce Gusto
- [ ] Cafetera Nespresso
- [ ] Cápsulas Nespresso

**Comment by diegok** [comment]
Yo comprare las pastas. Pillare 4 docenas!, y me llevare el mate ;-)

**Comment by frankiejol** [comment]
Yo llevo una nespresso y cápsulas
